// Supabase Types - Additional types for the application
// This file complements supabase.types.ts (generated by Supabase CLI)

export interface Branch {
  id: string;
  name: 'greenbelt' | 'podium' | 'mind_museum' | 'trinoma' | 'uptown';
  label: string;
  created_at: string;
  updated_at: string;
}

export interface DailyReportRow {
  id: string;
  branch_id: string;
  report_date: string;
  date_range_start: string;
  date_range_end: string;
  transactions_file_name: string | null;
  mapping_file_name: string | null;
  summary_json: any;
  user_id: string;
  created_at: string;
  updated_at: string;
  branch: Branch;
}

export interface MonthlyReportRow {
  id: string;
  branch_id: string | null;
  month_key: string;
  date_range_start: string;
  date_range_end: string;
  summary_json: any;
  user_id: string;
  created_at: string;
  updated_at: string;
  branch: Branch | null;
}

export interface SaveDailyReportPayload {
  branchId: string;
  reportDate: string;
  dateRangeStart: string;
  dateRangeEnd: string;
  transactionsFileName: string;
  mappingFileName?: string;
  summaryJson: Record<string, any>;
}

export interface SaveMonthlyReportPayload {
  branchId: string | null;
  monthKey: string;
  dateRangeStart: string;
  dateRangeEnd: string;
  summaryJson: Record<string, any>;
}

// ============================================================================
// USER PROFILE TYPES (ADMIN SYSTEM)
// ============================================================================

export type UserRole = 'admin' | 'user';

export interface UserProfile {
  id: string;
  user_id: string;
  email: string;
  role: UserRole;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateUserPayload {
  email: string;
  password: string;
  role?: UserRole;
}

export interface UpdateUserPayload {
  role?: UserRole;
}
