// Supabase Types - Additional types for the application
// This file complements supabase.types.ts (generated by Supabase CLI)

export interface Branch {
  id: string;
  name: string;
  label: string;
  created_at: string;
  updated_at: string;
}

export interface DailyReportRow {
  id: string;
  branch_id: string;
  report_date: string;
  date_range_start: string;
  date_range_end: string;
  transactions_file_name: string | null;
  mapping_file_name: string | null;
  summary_json: any;
  user_id: string;
  created_at: string;
  updated_at: string;
  branch: Branch;
}

export interface MonthlyReportRow {
  id: string;
  branch_id: string | null;
  month_key: string;
  date_range_start: string;
  date_range_end: string;
  summary_json: any;
  user_id: string;
  created_at: string;
  updated_at: string;
  branch: Branch | null;
}

export interface SaveDailyReportPayload {
  branchId: string;
  reportDate: string;
  dateRangeStart: string;
  dateRangeEnd: string;
  transactionsFileName: string;
  mappingFileName?: string;
  summaryJson: Record<string, any>;
}

export interface SaveMonthlyReportPayload {
  branchId: string | null;
  monthKey: string;
  dateRangeStart: string;
  dateRangeEnd: string;
  summaryJson: Record<string, any>;
}

// ============================================================================
// USER PROFILE TYPES (ADMIN SYSTEM)
// ============================================================================

export type UserRole = 'admin' | 'user' | 'viewer';

export interface UserProfile {
  id: string;
  user_id: string;
  email: string;
  role: UserRole;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  is_archived: boolean;
  archived_at: string | null;
}

export interface CreateUserPayload {
  email: string;
  password: string;
  role?: UserRole;
}

export interface UpdateUserPayload {
  role?: UserRole;
}

// ============================================================================
// AUDIT LOG TYPES
// ============================================================================

export type AuditAction =
  | 'login'
  | 'logout'
  | 'add_data'
  | 'edit_data'
  | 'delete_data'
  | 'generate_report'
  | 'export_report'
  | 'create_user'
  | 'update_user'
  | 'delete_user'
  | 'change_role'
  | 'reset_password'
  | 'create_branch'
  | 'update_branch'
  | 'create_mapping'
  | 'update_mapping'
  | 'delete_mapping';

export type AuditModule =
  | 'auth'
  | 'summary'
  | 'reports'
  | 'user_management'
  | 'settings'
  | 'branches'
  | 'mappings';

export interface AuditLog {
  id: string;
  user_id: string | null;
  user_email: string;
  user_role: string;
  action: AuditAction;
  module: AuditModule;
  target_type: string | null;
  target_id: string | null;
  target_name: string | null;
  details: string | null;
  metadata: Record<string, any>;
  branch_id: string | null;
  report_type: string | null;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
}

export interface LogAuditEventPayload {
  action: AuditAction;
  module: AuditModule;
  targetType?: string;
  targetId?: string;
  targetName?: string;
  details?: string;
  metadata?: Record<string, any>;
  branchId?: string | null;
  reportType?: string | null;
}

export interface ListAuditLogsParams {
  userId?: string;
  action?: AuditAction;
  module?: AuditModule;
  branchId?: string;
  dateFrom?: string;
  dateTo?: string;
  search?: string;
  page?: number;
  pageSize?: number;
}

// ============================================================================
// DIRECTORY LINK TYPES
// ============================================================================

export interface DirectoryLink {
  id: string;
  name: string;
  url: string;
  description: string | null;
  category: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateDirectoryLinkPayload {
  name: string;
  url: string;
  description?: string | null;
  category?: string | null;
  is_active?: boolean;
}

export interface UpdateDirectoryLinkPayload {
  name?: string;
  url?: string;
  description?: string | null;
  category?: string | null;
  is_active?: boolean;
}

export interface ListDirectoryLinksParams {
  q?: string;
  category?: string;
  active?: boolean;
  sort?: 'updatedAt' | 'createdAt' | 'name';
  order?: 'asc' | 'desc';
}

// ============================================================================
// GENERATED REPORT TYPES
// ============================================================================

export type ReportType =
  | "SALES_MIX_OVERVIEW"
  | "PRODUCT_MIX"
  | "PRODUCT_MIX_CHANNEL"
  | "TOP_5_PRODUCTS"
  | "RUNNING_SALES_MIX_CATEGORY"
  | "CATEGORY_PERFORMANCE"
  | "POUR_IT_FORWARD";

export interface GeneratedReportRow {
  id: string;
  user_id: string;
  title: string;
  report_type: ReportType;
  branch_id: string | null;
  branch_name: string;
  date_from: string;
  date_to: string;
  compare_from: string | null;
  compare_to: string | null;
  selected_categories: string[];
  filters: Record<string, any>;
  computed_data: Record<string, any>;
  created_at: string;
  updated_at: string;
}

export interface SaveGeneratedReportPayload {
  title: string;
  reportType: ReportType;
  branchId: string | null;
  branchName: string;
  dateFrom: string;
  dateTo: string;
  compareFrom?: string | null;
  compareTo?: string | null;
  selectedCategories: string[];
  filters: Record<string, any>;
  computedData: Record<string, any>;
}

// ============================================================================
// DAILY SUMMARY JSON (stored in reports_daily.summary_json)
// ============================================================================

export interface DailySummaryJSON {
  summaryTotalsByCat: Record<string, number>;
  summaryQuantitiesByCat: Record<string, number>;
  grandTotal: number;
  grandQuantity: number;
  percentByCat: Record<string, number>;
  totalRows: number;
  mappedRows: number;
  unmappedRows: number;
  skippedRows: number;
  rowDetails: any[];
  unmappedSummary: any[];
  filename: string;
  uploadedAt: number;
}
