import { normalizeText } from "./normalize";
import type { MappingEntry, Category } from "./types";

/**
 * Normalize an option string for consistent lookup.
 * Extends normalizeText() with option-specific cleanup:
 *   - "12oz."  → "12 oz"   (normalizeText handles 12oz→12 oz, we strip "oz.")
 *   - "12 oz." → "12 oz"
 *   - trailing period removed
 *   - pipe spacing normalized ("  |  " → " | ")
 */
function normalizeOption(opt: string): string {
  let t = normalizeText(opt);     // lowercase, collapse spaces, 12oz→12 oz
  t = t.replace(/\boz\./g, "oz"); // "12 oz." → "12 oz"
  t = t.replace(/\.$/, "");       // remove trailing period
  t = t.replace(/\s*\|\s*/g, " | "); // normalize pipe spacing
  return t.trim();
}

/**
 * Raw validation table extracted from VALIDATION DATA.xlsx.
 * Format: [mappedName, category, item, option]
 *
 * This is the authoritative mapping source.  370 rows total.
 * mappedCat      = mappedName (column index 0)
 * mappedItemName = item       (column index 2, unchanged)
 */
const RAW: [string, string, string, string][] = [
  // ── PACKAGING ─────────────────────────────────────────────────────────────
  ["PACKAGING","PACKAGING","12oz Bamboo Cup",""],
  ["PACKAGING","PACKAGING","16oz Bamboo Cup",""],
  ["PACKAGING","PACKAGING","12oz Iced Dabba Cup",""],
  ["PACKAGING","PACKAGING","16oz Iced Dabba Cup",""],
  ["PACKAGING","PACKAGING","8oz Paper Cup",""],
  ["PACKAGING","PACKAGING","12oz Paper Cup",""],
  ["PACKAGING","PACKAGING","16oz Paper Cup",""],
  ["PACKAGING","PACKAGING","Dagel Box of 3",""],
  ["PACKAGING","PACKAGING","Rice Straw",""],
  ["PACKAGING","PACKAGING","Delivery | Rice Straw",""],
  ["PACKAGING","PACKAGING","Delivery | Egg Carrier",""],
  ["PACKAGING","PACKAGING","Delivery | Paper Bag - Egg Tray",""],

  // ── ADD-ONS ───────────────────────────────────────────────────────────────
  ["ADD-ONS","ADD-ONS","Almond Milk",""],
  ["ADD-ONS","ADD-ONS","Black Sesame Cold Foam",""],
  ["ADD-ONS","ADD-ONS","Brown Sugar Syrup",""],
  ["ADD-ONS","ADD-ONS","Burnt Vanilla Syrup",""],
  ["ADD-ONS","ADD-ONS","Butterscotch Syrup",""],
  ["ADD-ONS","ADD-ONS","Caramelized Banana Syrup",""],
  ["ADD-ONS","ADD-ONS","Cereal Crunch",""],
  ["ADD-ONS","ADD-ONS","Chocolate Foam",""],
  ["ADD-ONS","ADD-ONS","Dehusk Coconut Milk",""],
  ["ADD-ONS","ADD-ONS","Espresso Shot",""],
  ["ADD-ONS","ADD-ONS","French Vanilla Syrup",""],
  ["ADD-ONS","ADD-ONS","Hojicha Powder",""],
  ["ADD-ONS","ADD-ONS","Honey Syrup",""],
  ["ADD-ONS","ADD-ONS","Lychee Syrup",""],
  ["ADD-ONS","ADD-ONS","Matcha Cream Foam",""],
  ["ADD-ONS","ADD-ONS","Matcha Powder",""],
  ["ADD-ONS","ADD-ONS","Oat Milk",""],
  ["ADD-ONS","ADD-ONS","Peanut Butter Syrup",""],
  ["ADD-ONS","ADD-ONS","Rock Salt Cheese Foam",""],
  ["ADD-ONS","ADD-ONS","Salted Cream Foam",""],
  ["ADD-ONS","ADD-ONS","Salted Caramel Foam",""],
  ["ADD-ONS","ADD-ONS","Salted Caramel Syrup",""],
  ["ADD-ONS","ADD-ONS","Signature Mocha Syrup",""],
  ["ADD-ONS","ADD-ONS","Spanish Latte Syrup",""],
  ["ADD-ONS","ADD-ONS","Strawberry Cream Foam",""],
  ["ADD-ONS","ADD-ONS","Strawberry Puree",""],
  ["ADD-ONS","ADD-ONS","Sugar Syrup",""],
  ["ADD-ONS","ADD-ONS","Vanilla Foam",""],
  ["ADD-ONS","ADD-ONS","Water Bottle",""],
  ["ADD-ONS","ADD-ONS","Whey Protein",""],
  ["ADD-ONS","ADD-ONS","White Chocolate Mocha Syrup",""],
  ["ADD-ONS","ADD-ONS","Yuzu Syrup",""],

  // ── DEL-ADD-ONS ───────────────────────────────────────────────────────────
  ["ADD-ONS","DEL-ADD-ONS","Almond Milk",""],
  ["ADD-ONS","DEL-ADD-ONS","Black Sesame Cold Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Brown Sugar Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Burnt Vanilla Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Butterscotch Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Caramelized Banana Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Cereal Crunch",""],
  ["ADD-ONS","DEL-ADD-ONS","Chocolate Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Dehusk Coconut Milk",""],
  ["ADD-ONS","DEL-ADD-ONS","Espresso Shot",""],
  ["ADD-ONS","DEL-ADD-ONS","French Vanilla Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Hojicha Powder",""],
  ["ADD-ONS","DEL-ADD-ONS","Honey Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Lychee Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Matcha Cream Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Matcha Powder",""],
  ["ADD-ONS","DEL-ADD-ONS","Oat Milk",""],
  ["ADD-ONS","DEL-ADD-ONS","Peanut Butter Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Rock Salt Cheese Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Salted Cream Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Salted Caramel Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Salted Caramel Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Signature Mocha Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Spanish Latte Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Strawberry Cream Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Strawberry Puree",""],
  ["ADD-ONS","DEL-ADD-ONS","Vanilla Foam",""],
  ["ADD-ONS","DEL-ADD-ONS","Whey Protein",""],
  ["ADD-ONS","DEL-ADD-ONS","White Chocolate Mocha Syrup",""],
  ["ADD-ONS","DEL-ADD-ONS","Yuzu Syrup",""],

  // ── CLASSICS ──────────────────────────────────────────────────────────────
  ["ICED","CLASSICS","Americano","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Americano","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Americano","Hot Regular 12oz."],
  ["HOT","CLASSICS","Americano","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Burnt Vanilla","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Burnt Vanilla","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Burnt Vanilla","Hot Regular 12oz."],
  ["HOT","CLASSICS","Burnt Vanilla","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Butterscotch","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Butterscotch","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Butterscotch","Hot Regular 12oz."],
  ["HOT","CLASSICS","Butterscotch","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Cold Brew","Regular 12 oz."],
  ["ICED","CLASSICS","Cold Brew","Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Dirty Matcha","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Dirty Matcha","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Dirty Matcha","Hot Regular 12oz."],
  ["HOT","CLASSICS","Dirty Matcha","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Latte","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Latte","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Latte","Hot Regular 12oz."],
  ["HOT","CLASSICS","Latte","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Matcha","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Matcha","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Matcha","Hot Regular 12oz."],
  ["HOT","CLASSICS","Matcha","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Salted Caramel","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Salted Caramel","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Salted Caramel","Hot Regular 12oz."],
  ["HOT","CLASSICS","Salted Caramel","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Signature Mocha","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Signature Mocha","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Signature Mocha","Hot Regular 12oz."],
  ["HOT","CLASSICS","Signature Mocha","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","Spanish Latte","Iced Regular 12 oz."],
  ["ICED","CLASSICS","Spanish Latte","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","Spanish Latte","Hot Regular 12oz."],
  ["HOT","CLASSICS","Spanish Latte","Hot Large 16 oz. (+10)"],
  ["ICED","CLASSICS","White Chocolate Mocha","Iced Regular 12 oz."],
  ["ICED","CLASSICS","White Chocolate Mocha","Iced Large 16 oz. (+10)"],
  ["HOT","CLASSICS","White Chocolate Mocha","Hot Regular 12oz."],
  ["HOT","CLASSICS","White Chocolate Mocha","Hot Large 16 oz. (+10)"],

  // ── DEL - CLASSICS ────────────────────────────────────────────────────────
  ["ICED","DEL - CLASSICS","Americano","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Americano","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Americano","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Americano","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Burnt Vanilla","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Burnt Vanilla","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Burnt Vanilla","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Burnt Vanilla","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Butterscotch","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Butterscotch","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Butterscotch","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Butterscotch","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Cold Brew","Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Cold Brew","Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Dirty Matcha","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Dirty Matcha","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Dirty Matcha","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Dirty Matcha","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Latte","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Latte","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Latte","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Latte","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Matcha","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Matcha","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Matcha","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Matcha","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Salted Caramel","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Salted Caramel","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Salted Caramel","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Salted Caramel","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Signature Mocha","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Signature Mocha","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Signature Mocha","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Signature Mocha","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","Spanish Latte","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","Spanish Latte","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","Spanish Latte","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","Spanish Latte","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - CLASSICS","White Chocolate Mocha","Iced Regular 12 oz."],
  ["ICED","DEL - CLASSICS","White Chocolate Mocha","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - CLASSICS","White Chocolate Mocha","Hot Regular 12oz."],
  ["HOT","DEL - CLASSICS","White Chocolate Mocha","Hot Large 16 oz. (+10)"],

  // ── DOT SIGNATURES ────────────────────────────────────────────────────────
  ["ICED","DOT SIGNATURES","Black Sesame Hojicha Latte","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Black Sesame Hojicha Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Caramelized Banana Hojicha Latte","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Caramelized Banana Hojicha Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Cereal Milk","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Cereal Milk","Iced Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Chocolate Milk","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Chocolate Milk","Iced Large 16 oz. (+10)"],
  ["HOT","DOT SIGNATURES","Chocolate Milk","Hot Regular 12 oz."],
  ["HOT","DOT SIGNATURES","Chocolate Milk","Hot Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Regular 12 oz. | Dairy"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Regular 12 oz. | Almond"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Regular 12 oz. | Oat"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Large 16 oz. (+10) | Dairy"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Large 16 oz. (+10) | Almond"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Large 16 oz. (+10) | Oat"],
  ["ICED","DOT SIGNATURES","Creamy Coco Matcha","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Creamy Coco Matcha","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Dirty Cereal Milk","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Dirty Cereal Milk","Iced Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Regular 12 oz. | Dairy"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Regular 12 oz. | Almond"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Regular 12 oz. | Oat"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Large 16 oz. (+10) | Dairy"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Large 16 oz. (+10) | Almond"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Large 16 oz. (+10) | Oat"],
  ["ICED","DOT SIGNATURES","Dot Latte","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Dot Latte","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Large 16 oz. (+10)"],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Regular 12 oz."],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Horchata","Regular 12 oz. | Dairy"],
  ["ICED","DOT SIGNATURES","Horchata","Regular 12 oz. | Almond"],
  ["ICED","DOT SIGNATURES","Horchata","Regular 12 oz. | Oat"],
  ["ICED","DOT SIGNATURES","Horchata","Large 16 oz. (+10) | Dairy"],
  ["ICED","DOT SIGNATURES","Horchata","Large 16 oz. (+10) | Almond"],
  ["ICED","DOT SIGNATURES","Horchata","Large 16 oz. (+10) | Oat"],
  ["ICED","DOT SIGNATURES","Malted Milk Protein Latte","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Malted Milk Protein Latte","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","PB Protein Latte","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","PB Protein Latte","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Salted Caramel Matcha","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Salted Caramel Matcha","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Salted Cream Matcha","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Salted Cream Matcha","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Salted Dark Chocolate","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Salted Dark Choc Protein Latte","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Salted Dark Choc Protein Latte","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Regular 12 oz. | Dairy"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Regular 12 oz. | Almond"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Regular 12 oz. | Oat"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Large 16 oz. (+10) | Dairy"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Large 16 oz. (+10) | Almond"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Large 16 oz. (+10) | Oat"],
  ["ICED","DOT SIGNATURES","Strawberry Cream Matcha","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Strawberry Cream Matcha","Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Strawberry Hojicha Latte","Iced Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Strawberry Hojicha Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DOT SIGNATURES","Strawberry Milk","Regular 12 oz."],
  ["ICED","DOT SIGNATURES","Tiramisu Cream Latte","Large 16 oz. (+10)"],

  // ── DEL - DOT SIGNATURES ──────────────────────────────────────────────────
  ["ICED","DEL - DOT SIGNATURES","Black Sesame Hojicha Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Black Sesame Hojicha Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Caramelized Banana Hojicha Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Caramelized Banana Hojicha Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Cereal Milk","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Cereal Milk","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Chocolate Milk","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Chocolate Milk","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - DOT SIGNATURES","Chocolate Milk","Hot Regular 12 oz."],
  ["HOT","DEL - DOT SIGNATURES","Chocolate Milk","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Cookie Butter Oat Latte","Regular 12 oz. | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Cookie Butter Oat Latte","Regular 12 oz. | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Cookie Butter Oat Latte","Regular 12 oz. | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Cookie Butter Oat Latte","Large 16 oz. (+10) | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Cookie Butter Oat Latte","Large 16 oz. (+10) | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Cookie Butter Oat Latte","Large 16 oz. (+10) | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Creamy Coco Matcha","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Creamy Coco Matcha","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Cereal Milk","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Dirty Cereal Milk","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Horchata","Regular 12 oz. | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Horchata","Regular 12 oz. | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Horchata","Regular 12 oz. | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Horchata","Large 16 oz. (+10) | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Horchata","Large 16 oz. (+10) | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Dirty Horchata","Large 16 oz. (+10) | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Dot Latte","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Dot Latte","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Hojicha Oat Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Hojicha Oat Latte","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - DOT SIGNATURES","Hojicha Oat Latte","Hot Regular 12 oz."],
  ["HOT","DEL - DOT SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Horchata","Regular 12 oz. | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Horchata","Regular 12 oz. | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Horchata","Regular 12 oz. | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Horchata","Large 16 oz. (+10) | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Horchata","Large 16 oz. (+10) | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Horchata","Large 16 oz. (+10) | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Malted Milk Protein Latte","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Malted Milk Protein Latte","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","PB Protein Latte","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","PB Protein Latte","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Salted Caramel Matcha","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Salted Caramel Matcha","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Salted Cream Matcha","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Salted Cream Matcha","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Salted Dark Chocolate","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Salted Dark Choc Protein Latte","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Salted Dark Choc Protein Latte","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Salted Honey Oat Latte","Regular 12 oz. | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Salted Honey Oat Latte","Regular 12 oz. | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Salted Honey Oat Latte","Regular 12 oz. | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Salted Honey Oat Latte","Large 16 oz. (+10) | Dairy"],
  ["ICED","DEL - DOT SIGNATURES","Salted Honey Oat Latte","Large 16 oz. (+10) | Almond"],
  ["ICED","DEL - DOT SIGNATURES","Salted Honey Oat Latte","Large 16 oz. (+10) | Oat"],
  ["ICED","DEL - DOT SIGNATURES","Strawberry Cream Matcha","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Strawberry Cream Matcha","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Strawberry Hojicha Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Strawberry Hojicha Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Strawberry Milk","Regular 12 oz."],
  ["ICED","DEL - DOT SIGNATURES","Strawberry Milk","Large 16 oz. (+10)"],
  ["ICED","DEL - DOT SIGNATURES","Tiramisu Cream Latte","Large 16 oz. (+10)"],

  // ── DEHUSK LINE ───────────────────────────────────────────────────────────
  ["ICED","DEHUSK LINE","Calamansi Coconut Latte","Iced Regular 12 oz."],
  ["ICED","DEHUSK LINE","Calamansi Coconut Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEHUSK LINE","Coco Chata","Iced Regular 12 oz."],
  ["ICED","DEHUSK LINE","Coco Chata","Iced Large 16 oz. (+10)"],
  ["ICED","DEHUSK LINE","Coconut Cream Cold Brew","Iced Regular 12 oz."],
  ["ICED","DEHUSK LINE","Coconut Cream Cold Brew","Iced Large 16 oz. (+10)"],

  // ── DEL - DEHUSK LINE ─────────────────────────────────────────────────────
  ["ICED","DEL - DEHUSK LINE","Calamansi Coconut Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DEHUSK LINE","Calamansi Coconut Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DEHUSK LINE","Coco Chata","Iced Regular 12 oz."],
  ["ICED","DEL - DEHUSK LINE","Coco Chata","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DEHUSK LINE","Coconut Cream Cold Brew","Iced Regular 12 oz."],
  ["ICED","DEL - DEHUSK LINE","Coconut Cream Cold Brew","Iced Large 16 oz. (+10)"],

  // ── DOT TEA LINE ──────────────────────────────────────────────────────────
  ["ICED","DOT TEA LINE","Mango Tea Latte","Iced Regular 12 oz."],
  ["ICED","DOT TEA LINE","Mango Tea Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DOT TEA LINE","Salted Cheese Tea Latte","Iced Regular 12 oz."],
  ["ICED","DOT TEA LINE","Salted Cheese Tea Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DOT TEA LINE","Signature Tea","Iced Regular 12 oz."],
  ["ICED","DOT TEA LINE","Signature Tea","Iced Large 16 oz. (+10)"],
  ["HOT","DOT TEA LINE","Signature Tea","Hot Regular 12oz"],
  ["HOT","DOT TEA LINE","Signature Tea","Hot Large 16 oz. (+10)"],
  ["ICED","DOT TEA LINE","Signature Tea Latte","Iced Regular 12 oz."],
  ["ICED","DOT TEA LINE","Signature Tea Latte","Iced Large 16 oz. (+10)"],
  ["HOT","DOT TEA LINE","Signature Tea Latte","Hot Regular 12oz"],
  ["HOT","DOT TEA LINE","Signature Tea Latte","Hot Large 16 oz. (+10)"],

  // ── DEL - DOT TEA LINE ────────────────────────────────────────────────────
  ["ICED","DEL - DOT TEA LINE","Mango Tea Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT TEA LINE","Mango Tea Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT TEA LINE","Salted Cheese Tea Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT TEA LINE","Salted Cheese Tea Latte","Iced Large 16 oz. (+10)"],
  ["ICED","DEL - DOT TEA LINE","Signature Tea","Iced Regular 12 oz."],
  ["ICED","DEL - DOT TEA LINE","Signature Tea","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - DOT TEA LINE","Signature Tea","Hot Regular 12oz"],
  ["HOT","DEL - DOT TEA LINE","Signature Tea","Hot Large 16 oz. (+10)"],
  ["ICED","DEL - DOT TEA LINE","Signature Tea Latte","Iced Regular 12 oz."],
  ["ICED","DEL - DOT TEA LINE","Signature Tea Latte","Iced Large 16 oz. (+10)"],
  ["HOT","DEL - DOT TEA LINE","Signature Tea Latte","Hot Regular 12oz"],
  ["HOT","DEL - DOT TEA LINE","Signature Tea Latte","Hot Large 16 oz. (+10)"],

  // ── SNACKS ────────────────────────────────────────────────────────────────
  ["SNACKS","SNACKS","Black & White Bar",""],
  ["SNACKS","SNACKS","Calamansi Protein Bar",""],
  ["SNACKS","SNACKS","Corned Beef Pandesal",""],
  ["SNACKS","SNACKS","Dark Chocolate Salt Bread",""],
  ["SNACKS","SNACKS","Double Chocolate Chip Cookies",""],
  ["SNACKS","SNACKS","Everything Dagel",""],
  ["SNACKS","SNACKS","Ham Egg and Cheese Dagel",""],
  ["SNACKS","SNACKS","Oatmeal Cookie Protein Bar",""],
  ["SNACKS","SNACKS","Oatmeal Protein Cookie",""],
  ["SNACKS","SNACKS","Peanut Butter Monkey Bar",""],
  ["SNACKS","SNACKS","Salt Bread",""],
  ["SNACKS","SNACKS","Spicy Tuna Pandesal",""],
  ["SNACKS","SNACKS","Spinach Mushroom Pandesal",""],
  ["SNACKS","SNACKS","Truffle Cheese Salt Bread",""],
  ["SNACKS","SNACKS","Roni Pizza Dagel",""],

  // ── DEL-SNACKS ────────────────────────────────────────────────────────────
  ["SNACKS","DEL-SNACKS","Black & White Bar",""],
  ["SNACKS","DEL-SNACKS","Calamansi Protein Bar",""],
  ["SNACKS","DEL-SNACKS","Corned Beef Pandesal",""],
  ["SNACKS","DEL-SNACKS","Dark Chocolate Salt Bread",""],
  ["SNACKS","DEL-SNACKS","Salt Bread",""],
  ["SNACKS","DEL-SNACKS","Double Chocolate Chip Cookies",""],
  ["SNACKS","DEL-SNACKS","Everything Dagel",""],
  ["SNACKS","DEL-SNACKS","Ham Egg and Cheese Dagel",""],
  ["SNACKS","DEL-SNACKS","Oatmeal Cookie Protein Bar",""],
  ["SNACKS","DEL-SNACKS","Oatmeal Protein Cookie",""],
  ["SNACKS","DEL-SNACKS","Peanut Butter Monkey Bar",""],
  ["SNACKS","DEL-SNACKS","Spicy Tuna Pandesal",""],
  ["SNACKS","DEL-SNACKS","Spinach Mushroom Pandesal",""],
  ["SNACKS","DEL-SNACKS","Truffle Cheese Salt Bread",""],
  ["SNACKS","DEL-SNACKS","Roni Pizza Dagel",""],

  // ── MERCH & PROMO ─────────────────────────────────────────────────────────
  ["MERCH","MERCH","Dc Tote Bag",""],
  ["PROMO","MERCH","GC 100",""],
  ["PROMO","MERCH","GC 300",""],
  ["PROMO","MERCH","GC 500",""],
  ["LOYALTY CARD","MERCH","Gift Card Sleeves",""],
  ["LOYALTY CARD","MERCH","FREE Gift Card Sleeves","total of 1000 php"],
  ["MERCH","MERCH","Tumbler Add-On","Set 1 (Straw + Rubber Stopper for Lid)"],
  ["MERCH","MERCH","Tumbler Add-On","Set 2 (Silicone Boot + Handle)"],
  ["MERCH","MERCH","Tumbler Holiday Set",""],
  ["MERCH","DEL-MERCH","Tumbler Add-On","Set 1 (Straw + Rubber Stopper for Lid)"],
  ["MERCH","DEL-MERCH","Tumbler Add-On","Set 2 (Silicone Boot + Handle)"],
  ["MERCH","DEL-MERCH","Tumbler Holiday Set","with extra straw"],
  ["MERCH","MERCH","Tumbler Only",""],

  // ── PROMO ─────────────────────────────────────────────────────────────────
  ["PROMO","PROMO","Bring your Own Tumbler",""],
  ["PROMO","PROMO","Gcash Food","100 pesos off"],
  ["PROMO","PROMO","Tumbler Only Promo Price","min.of 300 pesos"],
  ["PROMO","PROMO","Add Ons Set 1 Promo Price","straw + rubber stopper"],
  ["PROMO","PROMO","Add Ons Set 2 Promo Price","boot + handle"],
  ["ICED","PROMO","1 26 26 Promo Americano","Iced Regular 12 oz."],
  ["ICED","PROMO","1 26 26 Promo Latte","Iced Regular 12 oz."],

  // ── LOYALTY CARD ──────────────────────────────────────────────────────────
  ["LOYALTY CARD","LOYALTY CARD","LC Free Tumbler",""],
  ["LOYALTY CARD","LOYALTY CARD","LC Free Upsize",""],
];

/** Compiled mapping table with pre-normalized lookup keys. */
export const DEFAULT_MAPPING: MappingEntry[] = RAW.map(([mn, cat, item, opt]) => ({
  mappedName: mn as Category,
  category:   cat,
  item:       item,
  option:     opt,
  catNorm:    normalizeText(cat),
  itemNorm:   normalizeText(item),
  optionNorm: normalizeOption(opt),
}));

/** Exported for use in mapRow helpers. */
export { normalizeOption };
