import type { MappingEntry } from "./types";
import { toMappingEntries, normalizeOption } from "./validationMapping";

/**
 * Raw validation table extracted from public/Validation.xlsx (MENU 8172026).
 * Format: [mappedName, category, item, option]
 *
 * Add-on bucket rows are expanded at compile time (outputItem + flattened aliases).
 * Regenerated by: node scripts/generate-default-mapping.mjs
 */
const RAW: [string, string, string, string][] = [
  // ── PACKAGING / PACKAGING ──
  ["PACKAGING","PACKAGING","12oz Iced Dabba Cup",""],
  ["PACKAGING","PACKAGING","16oz Iced Dabba Cup",""],
  ["PACKAGING","PACKAGING","12oz Paper Cup",""],
  ["PACKAGING","PACKAGING","16oz Paper Cup",""],
  ["PACKAGING","PACKAGING","Dagel Box of 3",""],
  ["PACKAGING","PACKAGING","Straw",""],
  ["PACKAGING","PACKAGING","Delivery | Straw",""],
  ["PACKAGING","PACKAGING","Delivery | Egg Carrier",""],
  ["PACKAGING","PACKAGING","Delivery | Paper Bag - Egg Tray",""],

  // ── ADD-ONS / PACKAGING ──
  ["ADD-ONS","PACKAGING","Less Ice",""],
  ["ADD-ONS","PACKAGING","Less Sweet",""],
  ["ADD-ONS","PACKAGING","Half-Shot Espresso",""],
  ["ADD-ONS","PACKAGING","Warm",""],
  ["ADD-ONS","PACKAGING","Extra Hot",""],
  ["ADD-ONS","PACKAGING","No Ice",""],
  ["ADD-ONS","PACKAGING","No Sugar",""],
  ["ADD-ONS","PACKAGING","One Pump",""],
  ["ADD-ONS","PACKAGING","Splenda",""],
  ["ADD-ONS","PACKAGING","Sugar Granules",""],
  ["ADD-ONS","PACKAGING","Stirrer",""],

  // ── ADD-ONS / ADD-ONS ──
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Cereal Crunch"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Coconut Water"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Decaf Espresso Shot"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Espresso Shot"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Hojicha Powder"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Krea Creatine Wheyl"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Matcha Powder"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Water Bottle"],
  ["ADD-ONS","ADD-ONS","ADD ONS MISC","Whey Protein"],
  ["ADD-ONS","ADD-ONS","ADD ONS MILK","Almond Milk"],
  ["ADD-ONS","ADD-ONS","ADD ONS MILK","Dehusk Coconut Milk"],
  ["ADD-ONS","ADD-ONS","ADD ONS MILK","Oat Milk"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Brown Sugar Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Burnt Vanilla Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Butterscotch Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Caramelized Banana Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","French Vanilla Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Honey Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Peanut Butter Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Salted Caramel Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Signature Mocha Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Sugar Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Spanish Latte Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","Strawberry Puree"],
  ["ADD-ONS","ADD-ONS","ADD ONS SYRUPS","White Chocolate Mocha Syrup"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Black Sesame Cold Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Chocolate Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Hojicha Cold Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Malted Chocolate Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Matcha Cream Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Rock Salt Cheese Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Salted Caramel Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Salted Cream Foam"],
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Strawberry Cream Foam"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Americano","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Americano","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Americano","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Americano","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Burnt Vanilla","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Burnt Vanilla","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Burnt Vanilla","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Burnt Vanilla","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Butterscotch","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Butterscotch","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Butterscotch","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Butterscotch","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Cold Brew","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Cold Brew","Iced Large (16oz)"],
  ["ICED","DOT CLASSICS","Dirty Matcha","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Dirty Matcha","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Dirty Matcha","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Dirty Matcha","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Latte","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Latte","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Latte","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Latte","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Matcha","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Matcha","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Matcha","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Matcha","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Salted Caramel","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Salted Caramel","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Salted Caramel","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Salted Caramel","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Signature Mocha","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Signature Mocha","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Signature Mocha","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Signature Mocha","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","Spanish Latte","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","Spanish Latte","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","Spanish Latte","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","Spanish Latte","Hot Large (16oz)"],

  // ── ICED / DOT CLASSICS ──
  ["ICED","DOT CLASSICS","White Chocolate Mocha","Iced Regular (12oz)"],
  ["ICED","DOT CLASSICS","White Chocolate Mocha","Iced Large (16oz)"],

  // ── HOT / DOT CLASSICS ──
  ["HOT","DOT CLASSICS","White Chocolate Mocha","Hot Regular (12oz)"],
  ["HOT","DOT CLASSICS","White Chocolate Mocha","Hot Large (16oz)"],

  // ── ICED / DOT SIGNATURES ──
  ["ICED","DOT SIGNATURES","Black Sesame Hojicha Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Black Sesame Hojicha Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Caramelized Banana Hojicha Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Caramelized Banana Hojicha Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Cereal Milk","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Cereal Milk","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Chocolate Milk","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Chocolate Milk","Iced Large (16oz)"],

  // ── HOT / DOT SIGNATURES ──
  ["HOT","DOT SIGNATURES","Chocolate Milk","Hot Regular 12oz."],
  ["HOT","DOT SIGNATURES","Chocolate Milk","Hot Large 16oz."],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Regular 12oz."],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Regular 12oz. l Almond"],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Regular 12oz. l Dairy"],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10)"],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10) l Almond"],
  ["HOT","DOT SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10) l Dairy"],

  // ── ICED / DOT SIGNATURES ──
  ["ICED","DOT SIGNATURES","Coco Americano","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Coco Americano","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","CocoChata","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","CocoChata","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Coconut Cream Cold Brew","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Coconut Cream Cold Brew","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Iced Regular (12oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Iced Regular (12oz) l Almond"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Iced Regular (12oz) l Oat"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Iced Large (16oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Iced Large (16oz) l Almond"],
  ["ICED","DOT SIGNATURES","Cookie Butter Oat Latte","Iced Large (16oz) l Oat"],
  ["ICED","DOT SIGNATURES","Creamy Coco Hojicha","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Creamy Coco Hojicha","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Creamy Coco Matcha","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Creamy Coco Matcha","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Dirty Cereal","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Dirty Cereal","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Dirty Coco","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Dirty Coco","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Iced Regular (12oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Iced Regular (12oz) l Almond"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Iced Regular (12oz) l Oat"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Iced Large (16oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Iced Large (16oz) l Almond"],
  ["ICED","DOT SIGNATURES","Dirty Horchata","Iced Large (16oz) l Oat"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Regular (12oz) l Almond"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Regular (12oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Large (16oz) l Almond"],
  ["ICED","DOT SIGNATURES","Hojicha Oat Latte","Iced Large (16oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Horchata","Iced Regular (12oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Horchata","Iced Regular (12oz) l Almond"],
  ["ICED","DOT SIGNATURES","Horchata","Iced Regular (12oz) l Oat"],
  ["ICED","DOT SIGNATURES","Horchata","Iced Large (16oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Horchata","Iced Large (16oz) l Almond"],
  ["ICED","DOT SIGNATURES","Horchata","Iced Large (16oz) l Oat"],
  ["ICED","DOT SIGNATURES","Malted Chocolate Americano","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Malted Chocolate Americano","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Malted Milk Protein Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Malted Milk Protein Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Peanut Butter Protein Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Peanut Butter Protein Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Salted Caramel Matcha","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Salted Caramel Matcha","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Salted Cream Matcha","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Salted Cream Matcha","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Salted Dark Choc Protein Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Salted Dark Choc Protein Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Salted Dark Chocolate","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Iced Regular (12oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Iced Regular (12oz) l Almond"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Iced Regular (12oz) l Oat"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Iced Large (16oz) l Dairy"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Iced Large (16oz) l Almond"],
  ["ICED","DOT SIGNATURES","Salted Honey Oat Latte","Iced Large (16oz) l Oat"],
  ["ICED","DOT SIGNATURES","Shaken Coconut Cold Brew","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Shaken Creamy Lemonade","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Strawberry Cream Matcha","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Strawberry Cream Matcha","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Strawberry Hojicha Latte","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Strawberry Hojicha Latte","Iced Large (16oz)"],
  ["ICED","DOT SIGNATURES","Strawberry Milk","Iced Regular (12oz)"],
  ["ICED","DOT SIGNATURES","Strawberry Milk","Iced Large (16oz)"],

  // ── SNACKS / DOT SNACKS ──
  ["SNACKS","DOT SNACKS","Black & White Bar",""],
  ["SNACKS","DOT SNACKS","Blitz Bar","Dark Chocolate Dream"],
  ["SNACKS","DOT SNACKS","Blitz Bar","Classic Vanilla"],
  ["SNACKS","DOT SNACKS","Blitz Bar","Matcha Latte"],
  ["SNACKS","DOT SNACKS","Calamansi Protein Bar",""],
  ["SNACKS","DOT SNACKS","Chocolate Salt Bread",""],
  ["SNACKS","DOT SNACKS","Corned Beef Pandesal",""],
  ["SNACKS","DOT SNACKS","Double Chocolate Chip Cookie",""],
  ["SNACKS","DOT SNACKS","Everything Dagel",""],
  ["SNACKS","DOT SNACKS","Ham Egg and Cheese Dagel",""],
  ["SNACKS","DOT SNACKS","Oatmeal Crunch Protein Bar",""],
  ["SNACKS","DOT SNACKS","Oatmeal Protein Cookie",""],
  ["SNACKS","DOT SNACKS","Peanut Butter Monkey Bar",""],
  ["SNACKS","DOT SNACKS","Salt Bread",""],
  ["SNACKS","DOT SNACKS","Spinach Mushroom Pandesal",""],
  ["SNACKS","DOT SNACKS","Truffle Salt Bread",""],

  // ── MERCH / MERCH ──
  ["MERCH","MERCH","DC Tote Bag",""],

  // ── PROMO / MERCH ──
  ["PROMO","MERCH","GC 100",""],
  ["PROMO","MERCH","GC 300",""],
  ["PROMO","MERCH","GC 500",""],

  // ── MERCH / MERCH ──
  ["MERCH","MERCH","Gift Card Sleeves",""],
  ["MERCH","MERCH","FREE Gift Card Sleeves","total of 1000 php"],
  ["MERCH","MERCH","Tumbler Add-On","Set 1 (Straw + Rubber Stopper for Lid)"],
  ["MERCH","MERCH","Tumbler Add-On","Set 2 (Silicone Boot + Handle)"],
  ["MERCH","MERCH","Tumbler Holiday Set",""],
  ["MERCH","MERCH","Tumbler Only",""],

  // ── PROMO / PROMO ──
  ["PROMO","PROMO","Bring your Own Tumbler",""],

  // ── ICED / PROMO ──
  ["ICED","PROMO","GO Free Drink - Americano","Iced Regular (12oz)"],

  // ── PROMO / PROMO ──
  ["PROMO","PROMO","GO Free Drink - Americano","Hot Regular (12oz)"],

  // ── ICED / PROMO ──
  ["ICED","PROMO","GO Free Drink - Latte","Iced Regular (12oz)"],

  // ── PROMO / PROMO ──
  ["PROMO","PROMO","GO Free Drink - Latte","Hot Regular (12oz)"],

  // ── ICED / PROMO ──
  ["ICED","PROMO","GO Free Drink - Matcha","Iced Regular (12oz)"],

  // ── PROMO / PROMO ──
  ["PROMO","PROMO","GO Free Drink - Matcha","Hot Regular (12oz)"],

  // ── ICED / PROMO ──
  ["ICED","PROMO","GO Free Drink - Spanish Latte","Iced Regular (12oz)"],

  // ── PROMO / PROMO ──
  ["PROMO","PROMO","GO Free Drink - Spanish Latte","Hot Regular (12oz)"],

  // ── LOYALTY CARD / LOYALTY CARD ──
  ["LOYALTY CARD","LOYALTY CARD","LC Free Tumbler",""],
  ["LOYALTY CARD","LOYALTY CARD","LC Free Upsize",""],
  ["LOYALTY CARD","LOYALTY CARD","LC Free 16oz",""],

  // ── ADD-ONS / DEL-ADD-ONS ──
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Cereal Crunch"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Coconut Water"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Decaf Espresso Shot"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Espresso Shot"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Hojicha Powder"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Krea Creatine Wheyl"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Matcha Powder"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Water Bottle"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MISC","Whey Protein"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MILK","Almond Milk"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MILK","Dehusk Coconut Milk"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS MILK","Oat Milk"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Brown Sugar Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Burnt Vanilla Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Butterscotch Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Caramelized Banana Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","French Vanilla Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Honey Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Peanut Butter Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Salted Caramel Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Signature Mocha Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Sugar Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Spanish Latte Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","Strawberry Puree"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS SYRUPS","White Chocolate Mocha Syrup"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Chocolate Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Black Sesame Cold Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Hojicha Cold Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Malted Chocolate Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Matcha Cream Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Rock Salt Cheese Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Salted Caramel Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Salted Cream Foam"],
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Strawberry Cream Foam"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Americano","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Americano","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Americano","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Americano","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Burnt Vanilla","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Burnt Vanilla","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Burnt Vanilla","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Burnt Vanilla","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Butterscotch","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Butterscotch","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Butterscotch","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Butterscotch","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Cold Brew","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Cold Brew","Iced Large (16oz)"],
  ["ICED","DEL - CLASSICS","Dirty Matcha","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Dirty Matcha","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Dirty Matcha","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Dirty Matcha","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Latte","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Latte","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Latte","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Latte","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Matcha","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Matcha","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Matcha","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Matcha","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Salted Caramel","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Salted Caramel","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Salted Caramel","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Salted Caramel","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Signature Mocha","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Signature Mocha","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Signature Mocha","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Signature Mocha","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","Spanish Latte","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","Spanish Latte","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","Spanish Latte","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","Spanish Latte","Hot Large (16oz)"],

  // ── ICED / DEL - CLASSICS ──
  ["ICED","DEL - CLASSICS","White Chocolate Mocha","Iced Regular (12oz)"],
  ["ICED","DEL - CLASSICS","White Chocolate Mocha","Iced Large (16oz)"],

  // ── HOT / DEL - CLASSICS ──
  ["HOT","DEL - CLASSICS","White Chocolate Mocha","Hot Regular (12oz)"],
  ["HOT","DEL - CLASSICS","White Chocolate Mocha","Hot Large (16oz)"],

  // ── ICED / DEL - SIGNATURES ──
  ["ICED","DEL - SIGNATURES","Black Sesame Hojicha Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Black Sesame Hojicha Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Caramelized Banana Hojicha Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Caramelized Banana Hojicha Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Cereal Milk","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Cereal Milk","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Chocolate Milk","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Chocolate Milk","Iced Large (16oz)"],

  // ── HOT / DEL - SIGNATURES ──
  ["HOT","DEL - SIGNATURES","Chocolate Milk","Hot Regular 12oz."],
  ["HOT","DEL - SIGNATURES","Chocolate Milk","Hot Large 16oz."],

  // ── ICED / DEL - SIGNATURES ──
  ["ICED","DEL - SIGNATURES","Coco Americano","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Coco Americano","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","CocoChata","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","CocoChata","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Coconut Cream Cold Brew","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Coconut Cream Cold Brew","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Cookie Butter Oat Latte","Iced Regular (12oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Cookie Butter Oat Latte","Iced Regular (12oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Cookie Butter Oat Latte","Iced Regular (12oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Cookie Butter Oat Latte","Iced Large (16oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Cookie Butter Oat Latte","Iced Large (16oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Cookie Butter Oat Latte","Iced Large (16oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Creamy Coco Hojicha","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Creamy Coco Hojicha","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Creamy Coco Matcha","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Creamy Coco Matcha","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Dirty Cereal","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Dirty Cereal","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Dirty Coco","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Dirty Coco","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Dirty Horchata","Iced Regular (12oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Dirty Horchata","Iced Regular (12oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Dirty Horchata","Iced Regular (12oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Dirty Horchata","Iced Large (16oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Dirty Horchata","Iced Large (16oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Dirty Horchata","Iced Large (16oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Hojicha Oat Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Hojicha Oat Latte","Iced Regular (12oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Hojicha Oat Latte","Iced Regular (12oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Hojicha Oat Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Hojicha Oat Latte","Iced Large (16oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Hojicha Oat Latte","Iced Large (16oz) l Dairy"],
  ["HOT","DEL - SIGNATURES","Hojicha Oat Latte","Hot Regular 12oz."],
  ["HOT","DEL - SIGNATURES","Hojicha Oat Latte","Hot Regular 12oz. l Almond"],
  ["HOT","DEL - SIGNATURES","Hojicha Oat Latte","Hot Regular 12oz. l Dairy"],
  ["HOT","DEL - SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10)"],
  ["HOT","DEL - SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10) l Almond"],
  ["HOT","DEL - SIGNATURES","Hojicha Oat Latte","Hot Large 16 oz. (+10) l Dairy"],
  ["ICED","DEL - SIGNATURES","Horchata","Iced Regular (12oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Horchata","Iced Regular (12oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Horchata","Iced Regular (12oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Horchata","Iced Large (16oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Horchata","Iced Large (16oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Horchata","Iced Large (16oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Malted Chocolate Americano","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Malted Chocolate Americano","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Malted Milk Protein Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Malted Milk Protein Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Peanut Butter Protein Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Peanut Butter Protein Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Salted Caramel Matcha","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Salted Caramel Matcha","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Salted Cream Matcha","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Salted Cream Matcha","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Salted Dark Choc Protein Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Salted Dark Choc Protein Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Salted Dark Chocolate","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Salted Honey Oat Latte","Iced Regular (12oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Salted Honey Oat Latte","Iced Regular (12oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Salted Honey Oat Latte","Iced Regular (12oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Salted Honey Oat Latte","Iced Large (16oz) l Dairy"],
  ["ICED","DEL - SIGNATURES","Salted Honey Oat Latte","Iced Large (16oz) l Almond"],
  ["ICED","DEL - SIGNATURES","Salted Honey Oat Latte","Iced Large (16oz) l Oat"],
  ["ICED","DEL - SIGNATURES","Shaken Coconut Cold Brew","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Shaken Creamy Lemonade","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Strawberry Cream Matcha","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Strawberry Cream Matcha","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Strawberry Hojicha Latte","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Strawberry Hojicha Latte","Iced Large (16oz)"],
  ["ICED","DEL - SIGNATURES","Strawberry Milk","Iced Regular (12oz)"],
  ["ICED","DEL - SIGNATURES","Strawberry Milk","Iced Large (16oz)"],

  // ── SNACKS / DEL - SNACKS ──
  ["SNACKS","DEL - SNACKS","Black & White Bar",""],
  ["SNACKS","DEL - SNACKS","Calamansi Protein Bar",""],
  ["SNACKS","DEL - SNACKS","Chocolate Salt Bread",""],
  ["SNACKS","DEL - SNACKS","Corned Beef Pandesal",""],
  ["SNACKS","DEL - SNACKS","Double Chocolate Chip Cookie",""],
  ["SNACKS","DEL - SNACKS","Everything Dagel",""],
  ["SNACKS","DEL - SNACKS","Ham Egg and Cheese Dagel",""],
  ["SNACKS","DEL - SNACKS","Oatmeal Crunch Protein Bar",""],
  ["SNACKS","DEL - SNACKS","Oatmeal Protein Cookie",""],
  ["SNACKS","DEL - SNACKS","Peanut Butter Monkey Bar",""],
  ["SNACKS","DEL - SNACKS","Salt Bread",""],
  ["SNACKS","DEL - SNACKS","Spinach Mushroom Pandesal",""],
  ["SNACKS","DEL - SNACKS","Truffle Salt Bread",""],

  // ── MERCH / DEL - MERCH ──
  ["MERCH","DEL - MERCH","Tumbler Add-On","Set 1 (Straw + Rubber Stopper for Lid)"],
  ["MERCH","DEL - MERCH","Tumbler Add-On","Set 2 (Silicone Boot + Handle)"],
  ["MERCH","DEL - MERCH","Tumbler Holiday Set","with extra straw"],

  // ── ADD-ONS / ADD-ONS ──
  ["ADD-ONS","ADD-ONS","ADD ONS FOAM","Vanilla Foam"],

  // ── ADD-ONS / DEL-ADD-ONS ──
  ["ADD-ONS","DEL-ADD-ONS","ADD ONS FOAM","Vanilla Foam"],
];

/** Compiled mapping table with pre-normalized lookup keys. */
export const DEFAULT_MAPPING: MappingEntry[] = toMappingEntries(
  RAW.map(([mappedName, category, item, option]) => ({ mappedName, category, item, option })),
);

/** Exported for use in mapRow helpers. */
export { normalizeOption };
