import { normalizeText } from "./normalize";
import type { MappingEntry } from "./types";

/**
 * VALIDATION_MAPPING is the authoritative item mapping for DOT Coffee,
 * extracted directly from the Data Validation.xlsx file.
 *
 * Column semantics:
 *   CAT       — the final reporting category (e.g. "ICED", "HOT", "COLD BREW")
 *   ITEM_NAME — the canonical display name used in all reports
 *   UTAK      — the alias that appears in the raw UTAK POS CSV (rawItemName column)
 *
 * Rows where UTAK was "-" or empty in the xlsx are intentionally excluded
 * because they cannot match any CSV row by UTAK.  Those rows are VANTAGE-only
 * aliases and are not needed for the current CSV pipeline.
 *
 * Order matters for duplicate UTAK keys: the FIRST entry wins during index
 * construction (see buildValidationIndex in mapRow.ts).
 */
const VALIDATION_MAPPING_RAW: Omit<MappingEntry, "utakNorm" | "itemNameNorm">[] = [
  // ── ADD-ONS ───────────────────────────────────────────────────────────────
  { CAT: "ADD-ONS", ITEM_NAME: "Espresso Shot",                UTAK: "Espresso Shot (+25)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Espresso Shot",                UTAK: "Espresso Shot" },
  { CAT: "ADD-ONS", ITEM_NAME: "Whey Protein",                 UTAK: "Whey Protein" },
  { CAT: "ADD-ONS", ITEM_NAME: "Burnt Vanilla Syrup",          UTAK: "Burnt Vanilla Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Burnt Vanilla Syrup",          UTAK: "Burnt Vanilla Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "White Chocolate Mocha Syrup",  UTAK: "White Chocolate Mocha Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "White Chocolate Mocha Syrup",  UTAK: "White Chocolate Mocha Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Salted Caramel Syrup",         UTAK: "Salted Caramel Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Salted Caramel Syrup",         UTAK: "Salted Caramel Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Sugar Syrup",                  UTAK: "Sugar Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "French Vanilla Syrup",         UTAK: "French Vanilla Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "French Vanilla Syrup",         UTAK: "French Vanilla Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Honey Syrup",                  UTAK: "Honey Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Vanilla Foam",                 UTAK: "Vanilla Foam (+25)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Vanilla Foam",                 UTAK: "Vanilla Foam" },
  { CAT: "ADD-ONS", ITEM_NAME: "Condensed Milk Syrup",         UTAK: "Spanish Latte Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Condensed Milk Syrup",         UTAK: "Spanish Latte Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Condensed Milk Syrup",         UTAK: "Condensed Milk Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Condensed Milk Syrup",         UTAK: "Condensed Syrup-" },
  { CAT: "ADD-ONS", ITEM_NAME: "Butterscotch Syrup",           UTAK: "Butterscotch Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Butterscotch Syrup",           UTAK: "Butterscotch Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Chocolate Foam",               UTAK: "Chocolate Foam (+25)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Chocolate Foam",               UTAK: "Chocolate Foam" },
  { CAT: "ADD-ONS", ITEM_NAME: "Salted Caramel Foam",          UTAK: "Salted Caramel Foam (+25)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Salted Caramel Foam",          UTAK: "Salted Caramel Foam" },
  { CAT: "ADD-ONS", ITEM_NAME: "Signature Mocha Syrup",        UTAK: "Signature Mocha Syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Signature Mocha Syrup",        UTAK: "Signature Mocha Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Signature Mocha Syrup",        UTAK: "Sig Mocha Syrup-AD0011" },
  { CAT: "ADD-ONS", ITEM_NAME: "Signature Mocha Syrup",        UTAK: "SigMocha Syrup-AD0011" },
  { CAT: "ADD-ONS", ITEM_NAME: "Lemonade Syrup",               UTAK: "Lemonade Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Strawberry Puree",             UTAK: "Strawberry Puree" },
  { CAT: "ADD-ONS", ITEM_NAME: "Almond Milk",                  UTAK: "Almond Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "Dairy Milk",                   UTAK: "Dairy Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "Oat Milk",                     UTAK: "Oat Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "Soy Milk",                     UTAK: "Soy Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "Matcha Powder",                UTAK: "Matcha Powder" },
  { CAT: "ADD-ONS", ITEM_NAME: "Matcha Powder",                UTAK: "Matcha Powder-" },
  { CAT: "ADD-ONS", ITEM_NAME: "Blend It",                     UTAK: "Blend It (+30)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Blend It",                     UTAK: "Blend It" },
  { CAT: "ADD-ONS", ITEM_NAME: "Peanut Butter Syrup",          UTAK: "Peanut Butter Sauce" },
  { CAT: "ADD-ONS", ITEM_NAME: "Peanut Butter Syrup",          UTAK: "PB Syrup-" },
  { CAT: "ADD-ONS", ITEM_NAME: "Peanut Butter Syrup",          UTAK: "Peanut Butter Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Cookie Butter Syrup",          UTAK: "Cookie Butter syrup (+10)" },
  { CAT: "ADD-ONS", ITEM_NAME: "Cookie Butter Syrup",          UTAK: "Cookie Butter Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Grapefruit Syrup",             UTAK: "Grapefruit Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Brown Sugar Syrup",            UTAK: "Brown Sugar Syrup" },
  { CAT: "ADD-ONS", ITEM_NAME: "Cold Foam",                    UTAK: "Cold Foam" },
  { CAT: "ADD-ONS", ITEM_NAME: "12 oz Milk",                   UTAK: "12 oz Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "16 oz Milk",                   UTAK: "16 oz Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "8 oz Milk",                    UTAK: "8 oz Milk" },
  { CAT: "ADD-ONS", ITEM_NAME: "Water Bottle",                 UTAK: "Water Bottle" },

  // ── PACKAGING ─────────────────────────────────────────────────────────────
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Hot Cup",              UTAK: "12 oz Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Hot Cup",              UTAK: "12oz Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Hot Cup",              UTAK: "12oz Hot Cup Walk in" },
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Hot Cup-Eco",          UTAK: "12oz Hot Cup Walk in" },
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Iced Cup",             UTAK: "12oz Iced Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Iced Cup",             UTAK: "12 oz Iced Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "16 oz Iced Cup",             UTAK: "16oz Iced Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "16 oz Iced Cup",             UTAK: "16 oz Iced Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "16 oz Hot Cup",              UTAK: "16oz Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "16 oz Hot Cup",              UTAK: "16 oz Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "16 oz Hot Cup-Eco",          UTAK: "16oz Hot Cup Walk in" },
  { CAT: "PACKAGING", ITEM_NAME: "8 oz Hot Cup",               UTAK: "8oz Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "8 oz Hot Cup",               UTAK: "8 oz Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "8 oz Hot Lid",               UTAK: "Hot 8 oz Lid" },
  { CAT: "PACKAGING", ITEM_NAME: "12 oz Hot Lid",              UTAK: "Lid I Hot 12oz" },
  { CAT: "PACKAGING", ITEM_NAME: "Cold Cup Lid",               UTAK: "Cold Cup Lid" },
  { CAT: "PACKAGING", ITEM_NAME: "Cold Cup Lid",               UTAK: "Lid I Cold Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "Extra Cold Cup",             UTAK: "Extra Cold Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "Extra Hot Cup",              UTAK: "Extra Hot Cup" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Medium)",         UTAK: "Paper Bag (Medium)" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Medium)",         UTAK: "Delivery | Paper Bag (Medium)" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Medium)",         UTAK: "Delivery | Paper Bag" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Medium)",         UTAK: "Paper Bag" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Medium)",         UTAK: "Paperbag" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Small)",          UTAK: "Paper Bag (Small)" },
  { CAT: "PACKAGING", ITEM_NAME: "Paper Bag (Large)",          UTAK: "Delivery | Paper Bag (Large)" },
  { CAT: "PACKAGING", ITEM_NAME: "Parchment Paper",            UTAK: "Delivery | Parchment Paper" },
  { CAT: "PACKAGING", ITEM_NAME: "Delivery | Egg Carrier",     UTAK: "Delivery | Egg Carrier" },
  { CAT: "PACKAGING", ITEM_NAME: "Egg Tray",                   UTAK: "Delivery | Paper Bag - Egg Tray" },
  { CAT: "PACKAGING", ITEM_NAME: "Coffee Sleeves",             UTAK: "Coffee Sleeves" },
  { CAT: "PACKAGING", ITEM_NAME: "Rice Straw Big",             UTAK: "Rice Straw (Big)" },
  { CAT: "PACKAGING", ITEM_NAME: "Rice Straw Small",           UTAK: "Rice Straw (Small)" },
  { CAT: "PACKAGING", ITEM_NAME: "Box of 3 Dagels",            UTAK: "Dagel box of 3" },
  { CAT: "PACKAGING", ITEM_NAME: "Box of 3 Dagels",            UTAK: "Box of 3 Dagels" },
  { CAT: "PACKAGING", ITEM_NAME: "Donut Box",                  UTAK: "Donut Box" },
  { CAT: "PACKAGING", ITEM_NAME: "Donut Pouch",                UTAK: "Donut Pouch" },

  // ── COLD BREW ─────────────────────────────────────────────────────────────
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Matcha",                        UTAK: "Bottled Matcha" },
  { CAT: "COLD BREW", ITEM_NAME: "Canned Dirty Matcha Cold Brew",         UTAK: "Bottled Dirty Matcha Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Canned Dirty Matcha Cold Brew",         UTAK: "Bottled Dirty Matcha" },
  { CAT: "COLD BREW", ITEM_NAME: "Canned Dirty Matcha Cold Brew",         UTAK: "Dirty Matcha Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Canned Dirty Matcha Cold Brew",         UTAK: "Canned Dirty Matcha" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Cold Brew",                     UTAK: "Bottled Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Salted Caramel Cold Brew",      UTAK: "Bottled Salted Caramel Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Salted Caramel Cold Brew",      UTAK: "Bottled Salted Caramel" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Spanish Latte Cold Brew",       UTAK: "Bottled Spanish Latte Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Cold Brew set of 3",            UTAK: "Bottled Cold Brew set of 3" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled White Chocolate Cold Brew",     UTAK: "Bottled White Chocolate Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Cold Brew Latte",               UTAK: "Bottled Cold Brew Latte" },
  { CAT: "COLD BREW", ITEM_NAME: "Best Sellers Bundle",                   UTAK: "Best Sellers Bundle" },
  { CAT: "COLD BREW", ITEM_NAME: "Bottled Spanish Latte Cold Brew set of 3", UTAK: "Bottled Spanish Latte Cold Brew set of 3" },
  { CAT: "COLD BREW", ITEM_NAME: "Sampler Bundle",                        UTAK: "Sampler Bundle" },
  { CAT: "COLD BREW", ITEM_NAME: "Salted Caramel Cold Brew",              UTAK: "Salted Caramel Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Spanish Latte Cold Brew",               UTAK: "Spanish Latte Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "White Chocolate Cold Brew",             UTAK: "White Chocolate Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "White Chocolate Cold Brew",             UTAK: "Canned White Chocolate Mocha" },
  { CAT: "COLD BREW", ITEM_NAME: "Matcha Cold Brew",                      UTAK: "Matcha Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Dirty Matcha Cold Brew",                UTAK: "Dirty Matcha Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Classic Cold Brew",                     UTAK: "Classic Cold Brew" },
  { CAT: "COLD BREW", ITEM_NAME: "Classic Cold Brew",                     UTAK: "Cold Brew Classic Bundle" },

  // ── CANNED ESPRESSO ───────────────────────────────────────────────────────
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Americano",          UTAK: "Bottled Americano" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Americano",          UTAK: "Canned Americano" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Burnt Vanilla",      UTAK: "Bottled Burnt Vanilla" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Burnt Vanilla",      UTAK: "Canned Burnt Vanilla Latte" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Spanish Latte",      UTAK: "Bottled Spanish Latte" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Spanish Latte",      UTAK: "Canned Spanish Latte" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Signature Mocha",    UTAK: "Bottled Signature Mocha" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Signature Mocha",    UTAK: "Canned Signature Mocha" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Horchata",           UTAK: "Canned Horchata" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Dirty Horchata",     UTAK: "Canned Dirty Horchata" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Salted Caramel Latte", UTAK: "Canned Salted Caramel Latte" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Matcha",             UTAK: "Canned Matcha" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Canned Latte",              UTAK: "Canned Latte" },
  { CAT: "CANNED ESPRESSO", ITEM_NAME: "Cold Brew Latte",           UTAK: "Cold Brew Latte" },

  // ── HOT ───────────────────────────────────────────────────────────────────
  { CAT: "HOT", ITEM_NAME: "Hot Dirty Matcha",              UTAK: "Hot Dirty Matcha" },
  { CAT: "HOT", ITEM_NAME: "Hot Matcha",                    UTAK: "Hot Matcha" },
  { CAT: "HOT", ITEM_NAME: "Hot Spanish Latte",             UTAK: "Hot Spanish Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Latte",                     UTAK: "Hot Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Latte",                     UTAK: "Hot Late" },
  { CAT: "HOT", ITEM_NAME: "Hot Dirty Chai Tea Latte",      UTAK: "Hot Dirty Chai Tea Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Americano",                 UTAK: "Hot Americano" },
  { CAT: "HOT", ITEM_NAME: "Hot Matcha Chai Tea Latte",     UTAK: "Hot Matcha Chai Tea Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Matcha Chai Tea Latte",     UTAK: "Matcha Chai-50010" },
  { CAT: "HOT", ITEM_NAME: "Hot Salted Caramel",            UTAK: "Hot Salted Caramel" },
  { CAT: "HOT", ITEM_NAME: "Hot Felling Better Tea Bag",    UTAK: "Hot Felling Better Tea Bag" },
  { CAT: "HOT", ITEM_NAME: "Hot Burnt Vanilla",             UTAK: "Hot Burnt Vanilla" },
  { CAT: "HOT", ITEM_NAME: "Hot Signature Mocha",           UTAK: "Hot Signature Mocha" },
  { CAT: "HOT", ITEM_NAME: "Hot White Chocolate Mocha",     UTAK: "Hot White Chocolate Mocha" },
  { CAT: "HOT", ITEM_NAME: "Hot Chai Tea Latte",            UTAK: "Hot Chai Tea Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Chai Tea Latte",            UTAK: "Hot Chai Tea-773071" },
  { CAT: "HOT", ITEM_NAME: "Hot Butterscotch",              UTAK: "Hot Butterscotch" },
  { CAT: "HOT", ITEM_NAME: "Hot Chocolate Horchata",        UTAK: "Hot Chocolate Horchata" },
  { CAT: "HOT", ITEM_NAME: "Hot Solo Espresso",             UTAK: "Solo Espresso" },
  { CAT: "HOT", ITEM_NAME: "Hot Solo Espresso",             UTAK: "Espresso 8oz-" },
  { CAT: "HOT", ITEM_NAME: "Hot Golden Matcha Oat Milk Latte", UTAK: "Hot Golden Matcha Oat Milk Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Golden Oat Milk Latte",     UTAK: "Hot Golden Oat Milk Latte" },
  { CAT: "HOT", ITEM_NAME: "CitrusAloeTea",                 UTAK: "Citrus Aloe Tea" },
  { CAT: "HOT", ITEM_NAME: "Hot Dirty Gingerbread Latte",   UTAK: "Hot Dirty Gingerbread Latte" },
  { CAT: "HOT", ITEM_NAME: "Hot Dirty Chocolate Horchata",  UTAK: "Hot Dirty Chocolate Horchata" },

  // ── ICED ──────────────────────────────────────────────────────────────────
  // Explicit temperature-prefixed UTAK entries (direct exact matches)
  { CAT: "ICED", ITEM_NAME: "Iced Golden Oat Milk Latte",         UTAK: "Iced Golden Oat Milk Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Honey Oat Latte",        UTAK: "Iced Salted Honey Oat Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Horchata",                UTAK: "Iced Dirty Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced Horchata",                      UTAK: "Iced Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced Latte",                         UTAK: "Iced Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "Iced Spanish Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Americano",                     UTAK: "Iced Americano" },
  { CAT: "ICED", ITEM_NAME: "Iced Burnt Vanilla",                 UTAK: "Iced Burnt Vanilla" },
  { CAT: "ICED", ITEM_NAME: "Iced Signature Mocha",               UTAK: "Iced Signature Mocha" },
  { CAT: "ICED", ITEM_NAME: "Iced Cold Brew",                     UTAK: "Cold Brew" },
  { CAT: "ICED", ITEM_NAME: "Iced Butterscotch",                  UTAK: "Iced Butterscotch" },
  { CAT: "ICED", ITEM_NAME: "Iced Cookie Butter Oat Latte",       UTAK: "Iced Cookie Butter Oat Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced White Chocolate Mocha",         UTAK: "Iced White Chocolate Mocha" },
  { CAT: "ICED", ITEM_NAME: "Iced Golden Matcha Oat Milk Latte",  UTAK: "Iced Golden Matcha Oat Milk Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Matcha",                  UTAK: "Iced Dirty Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Matcha",                        UTAK: "Iced Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Caramel Matcha",         UTAK: "Iced Salted Caramel Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Caramel",                UTAK: "Iced Salted Caramel" },
  { CAT: "ICED", ITEM_NAME: "Iced Wake Me Up Latte",              UTAK: "Iced Wake Me Up Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Chai Tea Latte",                UTAK: "Iced Chai Tea Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Chai Tea Latte",                UTAK: "Iced Chai Tea-02034-16-01" },
  { CAT: "ICED", ITEM_NAME: "Iced Chai Tea Latte",                UTAK: "IcedChaiTea-02034-16-01" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Chai Tea Latte",          UTAK: "Iced Dirty Chai Tea Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Chai Tea Latte",          UTAK: "Iced Dirty Chai Tea-02035-16-01" },
  { CAT: "ICED", ITEM_NAME: "Iced Peanut Butter Protein Latte",   UTAK: "Peanut Butter Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Peanut Butter Protein Latte",   UTAK: "Iced Peanut Butter Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Peanut Butter Protein Latte",   UTAK: "Iced PB Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Cereal Milk Latte",       UTAK: "Iced Dirty Cereal Milk Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Matcha Chai Tea Latte",         UTAK: "Iced Matcha Chai Tea Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Dark Choc Protein Latte",UTAK: "Salted Dark Choc Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Dark Choc Protein Latte",UTAK: "Iced Salted Dark Choc Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Dark Choc Protein Latte",UTAK: "Iced Salted Dark Chocolate" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Dark Choc Protein Latte",UTAK: "Iced Snickers Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Dark Choc Protein Latte",UTAK: "Snickers Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Gingerbread Latte",       UTAK: "Dirty Gingerbread Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Peppermint Matcha",             UTAK: "Peppermint Matcha" },
  { CAT: "ICED", ITEM_NAME: "Gingerbread Latte",                  UTAK: "Gingerbread Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Peppermint Matcha",       UTAK: "Dirty Peppermint Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Berry Matcha",                  UTAK: "Iced Berry Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Chocolate Horchata",      UTAK: "Dirty Chocolate Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced Dirty Chocolate Horchata",      UTAK: "Iced Dirty Chocolate Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced Chocolate Horchata",            UTAK: "Chocolate Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced Chocolate Horchata",            UTAK: "Iced Chocolate Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced White Chocolate Matcha",        UTAK: "Iced White Chocolate Matcha" },
  { CAT: "ICED", ITEM_NAME: "Am Lemonade Fizz",                   UTAK: "Am Lemonade Fizz" },
  { CAT: "ICED", ITEM_NAME: "Americano Fizz",                     UTAK: "Americano Fizz" },
  { CAT: "ICED", ITEM_NAME: "Double Berry Vanilla Fizz",          UTAK: "Double Berry Vanilla Fizz" },
  { CAT: "ICED", ITEM_NAME: "Iced Grapefruit Fizz",               UTAK: "Grapefruit Fizz" },
  { CAT: "ICED", ITEM_NAME: "Iced Pink Lychee Fizz",              UTAK: "Pink Lychee Fizz" },
  { CAT: "ICED", ITEM_NAME: "Iced Matcha Horchata",               UTAK: "Iced Matcha Horchata" },
  { CAT: "ICED", ITEM_NAME: "Iced Malted Milk Protein Latte",     UTAK: "Malted Milk Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Malted Milk Protein Latte",     UTAK: "Iced Malted Milk Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Strawberry Matcha",             UTAK: "Iced Strawberry Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Ube & Cheese Protein Latte",    UTAK: "Iced Ube & Cheese Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Ube & Cheese Protein Latte",    UTAK: "Ube & Cheese Protein Latte" },
  { CAT: "ICED", ITEM_NAME: "Citrus Aloe Iced Tea",               UTAK: "Citrus Aloe Iced Tea" },
  { CAT: "ICED", ITEM_NAME: "Iced Salted Cream Matcha",           UTAK: "Iced Salted Cream Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Strawberry Cream Matcha",       UTAK: "Iced Strawberry Cream Matcha" },
  { CAT: "ICED", ITEM_NAME: "Iced Creamy Coco Matcha",            UTAK: "Iced Creamy Coco Matcha" },

  // Explicit no-prefix aliases (POS sends bare base name; validate file maps
  // these to the correct canonical ICED item without needing temperature detection)
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "Spanish Latte" },
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "Spanish Latte Large 16 oz" },
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "Spanish Latte - Promo" },
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "12oz Iced Spanish Latte P80" },
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "12oz Hot Spanish Latte P80" },
  { CAT: "ICED", ITEM_NAME: "Iced Spanish Latte",                 UTAK: "12oz Hot Spanish Latte  P80" },

  // ── LOYALTY CARD ──────────────────────────────────────────────────────────
  { CAT: "LOYALTY CARD", ITEM_NAME: "LC 10 off instagram follow", UTAK: "LC 10 off instagram follow" },
  { CAT: "LOYALTY CARD", ITEM_NAME: "LC Free upsize",             UTAK: "LC Free upsize" },
  { CAT: "LOYALTY CARD", ITEM_NAME: "LC Free 12 oz Iced drink",   UTAK: "LC Free 12 oz Iced drink" },
  { CAT: "LOYALTY CARD", ITEM_NAME: "LC Free tumbler",            UTAK: "LC Free tumbler" },
  // "Gift Card Sleeves" is LOYALTY CARD — explicit exact override in mapRow guards this
  { CAT: "LOYALTY CARD", ITEM_NAME: "Gift Card Sleeves",          UTAK: "Gift Card Sleeves" },

  // ── MERCH ─────────────────────────────────────────────────────────────────
  { CAT: "MERCH", ITEM_NAME: "DC Blue Tote Bag",                  UTAK: "DC Blue Tote Bag" },
  { CAT: "MERCH", ITEM_NAME: "DC Clear Tumbler",                  UTAK: "DC Clear Tumbler" },
  { CAT: "MERCH", ITEM_NAME: "DC Clear Tumbler",                  UTAK: "DC ClearTumbler" },
  { CAT: "MERCH", ITEM_NAME: "Tumbler Only Promo Price",          UTAK: "Tumbler Only Promo Price" },
  { CAT: "MERCH", ITEM_NAME: "DC White Tumbler w/Sticker",        UTAK: "WhiteTumblerw/Stkr" },
  // "FREE Gift Card Sleeves" is MERCH per validation file — exact UTAK match
  { CAT: "MERCH", ITEM_NAME: "FREE Gift Card Sleeves",            UTAK: "FREE Gift Card Sleeves" },

  // ── SNACKS ────────────────────────────────────────────────────────────────
  { CAT: "SNACKS", ITEM_NAME: "Black & White Bar",                UTAK: "Black & White Bar" },
  { CAT: "SNACKS", ITEM_NAME: "Peanut Butter Monkey Bar",         UTAK: "Peanut Butter Monkey Bar" },
  { CAT: "SNACKS", ITEM_NAME: "Ham Egg and Cheese Dagel",         UTAK: "Ham and Cheese Donut Sandwich" },
  { CAT: "SNACKS", ITEM_NAME: "Ham Egg and Cheese Dagel",         UTAK: "Ham Egg and Cheese Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Protein Oat Cookie",               UTAK: "Protein Oat Cookie" },
  { CAT: "SNACKS", ITEM_NAME: "Protein Oat Cookie",               UTAK: "Oatmeal Protein Cookie" },
  { CAT: "SNACKS", ITEM_NAME: "Spicy Tuna Dagel",                 UTAK: "Spicy Tuna Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Spicy Tuna Dagel",                 UTAK: "Spicy Tuna Melt Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Everything Dagel",                 UTAK: "Everything Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Cardamom Dagel",                   UTAK: "Cardamom Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Ferrero Dagel",                    UTAK: "Ferrero Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Bar Bundle of 6 half and half",    UTAK: "Bar Bundle of 6 half and half" },
  { CAT: "SNACKS", ITEM_NAME: "Milk and Cheese Dagel",            UTAK: "Milk and Cheese Dagel" },
  { CAT: "SNACKS", ITEM_NAME: "Dulce de Leche Donut",             UTAK: "Dulce de Leche Donut" },
  { CAT: "SNACKS", ITEM_NAME: "Calamansi Brulee Donut",           UTAK: "Calamansi Brulee Donut" },
  { CAT: "SNACKS", ITEM_NAME: "Truffle Cheese Salt Bread",        UTAK: "Truffle Cheese Salt Bread" },
  { CAT: "SNACKS", ITEM_NAME: "Bar Bundle of 6 all black and white", UTAK: "Bar Bundle of 6 all black and white" },
  { CAT: "SNACKS", ITEM_NAME: "Bar Sampler",                      UTAK: "Bar Sampler" },
  { CAT: "SNACKS", ITEM_NAME: "Oatmeal Crunch Protein Bar",       UTAK: "Oatmeal Crunch Bar" },
  { CAT: "SNACKS", ITEM_NAME: "Oatmeal Crunch Protein Bar",       UTAK: "Oatmeal Crunch Protein Bar" },
  { CAT: "SNACKS", ITEM_NAME: "Oatmeal Crunch Protein Bar",       UTAK: "Oatmeal Cookie Protein Bar" },
  { CAT: "SNACKS", ITEM_NAME: "Calamansi Protein Bar",            UTAK: "Calamansi Protein Bar" },
  { CAT: "SNACKS", ITEM_NAME: "Heart Shaped Ferrero Box of 3",    UTAK: "Heart Shaped Ferrero Box of 3" },
  { CAT: "SNACKS", ITEM_NAME: "Savory Dagel Set of 3",            UTAK: "Savory Dagel Set of 3" },
  { CAT: "SNACKS", ITEM_NAME: "Sweet Dagel Set of 3",             UTAK: "Sweet Dagel Set of 3" },

  // ── PROMO ─────────────────────────────────────────────────────────────────
  { CAT: "PROMO", ITEM_NAME: "Bring your Own Tumbler",            UTAK: "Bring your Own Tumbler" },
  { CAT: "PROMO", ITEM_NAME: "BRING YOUR OWN DOT TUMBLER",        UTAK: "BRING YOUR OWN DOT TUMBLER" },
  { CAT: "PROMO", ITEM_NAME: "FREE UPSIZE",                       UTAK: "FREE UPSIZE" },
  { CAT: "PROMO", ITEM_NAME: "Iced 1 26 26 Promo Latte",          UTAK: "Iced 1 26 26 Promo Latte" },
  { CAT: "PROMO", ITEM_NAME: "Iced 1 26 26 Promo Americano",      UTAK: "Iced 1 26 26 Promo Americano" },
];

/** Compiled mapping table with normalized lookup keys. */
export const DEFAULT_MAPPING: MappingEntry[] = VALIDATION_MAPPING_RAW
  .filter(m => {
    const u = m.UTAK.trim();
    return u !== "" && u !== "-";
  })
  .map(m => ({
    ...m,
    utakNorm:     normalizeText(m.UTAK),
    itemNameNorm: normalizeText(m.ITEM_NAME),
  }));
