import jsPDF from "jspdf";
import "jspdf-autotable";

import type { Category } from "@/utils/types";

export interface RankedCategory {
  rank: number;
  category: Category;
  total: number;
  percentOfTotal: number;
}

interface ExportOptions {
  rankedCategories: RankedCategory[];
  branchLabel: string;
  dateRangeLabel: string;
  totalSales: number;
}

export async function exportCategoryRankingPdf(options: ExportOptions) {
  const { rankedCategories, branchLabel, dateRangeLabel, totalSales } = options;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  });

  const marginLeft = 56;
  let cursorY = 60;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("DOT Coffee - Summary Report", marginLeft, cursorY);

  cursorY += 24;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const generatedAt = new Date().toLocaleString();
  doc.text(`Generated: ${generatedAt}`, marginLeft, cursorY);

  cursorY += 20;

  doc.setFont("helvetica", "bold");
  doc.text("Branch:", marginLeft, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(branchLabel || "All branches", marginLeft + 55, cursorY);

  cursorY += 18;

  doc.setFont("helvetica", "bold");
  doc.text("Date range:", marginLeft, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(dateRangeLabel || "All dates", marginLeft + 70, cursorY);

  cursorY += 24;

  doc.setFont("helvetica", "bold");
  doc.text("Total Sales:", marginLeft, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(formatCurrency(totalSales), marginLeft + 80, cursorY);

  cursorY += 30;

  // Table header + rows
  // @ts-ignore - jsPDF autoTable typings are not bundled by default
  doc.autoTable({
    startY: cursorY,
    head: [["Rank", "Category", "Total Sales", "% of Total"]],
    body: rankedCategories.map((row) => [
      String(row.rank),
      row.category,
      formatCurrency(row.total),
      `${row.percentOfTotal.toFixed(1)}%`,
    ]),
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 6,
    },
    headStyles: {
      fillColor: [43, 103, 178], // #2B67B2
      textColor: 255,
    },
    alternateRowStyles: {
      fillColor: [247, 249, 252], // #F7F9FC
    },
    theme: "striped",
    margin: { left: marginLeft, right: marginLeft },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    "Generated by DOT Coffee Daily Ledger",
    marginLeft,
    pageHeight - 40,
  );

  doc.save("dot-coffee-summary.pdf");
}

function formatCurrency(value: number) {
  return `₱${value.toLocaleString("en-PH", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  })}`;
}

